/* ── IPC channel names ── */
export const Channels = {
  CHOOSE_SOURCES: 'dialog:choose-sources',
  CHOOSE_FILES: 'dialog:choose-files',
  CHOOSE_FOLDER: 'dialog:choose-folder',
  SCAN_INPUTS: 'files:scan-inputs',
  SCAN_PROGRESS: 'files:scan-progress',
  CANCEL_SCAN: 'files:cancel-scan',
  LOAD_PRESETS: 'presets:load-defaults',
  SAVE_PRESET: 'presets:save',
  DELETE_PRESET: 'presets:delete',
  GENERATE_PREVIEW: 'preview:generate',
  GENERATE_THUMBNAIL: 'preview:thumbnail',
  PLAN_BATCH: 'batch:plan-output',
  RUN_BATCH: 'batch:run',
  BATCH_PROGRESS: 'batch:progress',
  CANCEL_BATCH: 'batch:cancel',
  OPEN_FOLDER: 'shell:open-folder',
  OPEN_RMBG_MODEL_PAGE: 'shell:open-rmbg-model-page',
  EXPORT_ERROR_LOG: 'batch:export-error-log',
  DROP_FILES: 'files:drop',
  SESSION_SAVE: 'session:save',
  SESSION_LOAD: 'session:load',
  BACKGROUND_REMOVER_STATUS: 'background-remover:status',
  RUN_BACKGROUND_REMOVAL: 'background-remover:run',
  BACKGROUND_REMOVAL_PROGRESS: 'background-remover:progress',
  CANCEL_BACKGROUND_REMOVAL: 'background-remover:cancel',
  GENERATE_FAVICON_BUNDLE: 'favicon:generate-bundle',
} as const;
